appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: LpORv7uDDPS+gcZRq/1NfbzeQZScuylbyM+4BxgXzVl3WOY8ZJ7XReQok6KQjy0aLwinsLnZy8g+nzjr51R2TZXTL/IZ1UXz65xTXt38tyMq0ymsi9AwltSUpBWCQ6Z/e/9co9cX2rvCtJ23be1P2pZe8fcy0S/2V4wvBqOost/3DgvmO1V/MwYjj7qhJNSxDL5Zj02TlQ3h7dM6xLQXiMM4PysAg4LI+FFDudIhhwi8E8GzcWm3+nB7NXq0CK2ybtsRd0sDklNPpKvJ8PmEDEBgNkk4SOT6JaSNWouDOlhpeg7jLzGyAau6EjIfeMxTayTd2fWd7i7cz4TxruJiZ4nce/dDqBz2jzUNVoP7HwX+4Z3fRTg8KGSqfDPxgUNQWWi6xMBua7n5gmSFxyA6WjJTLGpqWRMQ0NHpSvqUVTL8uLVqypiuKEipLQ896suJhSwxy6+I6x60w0qte6h/ecU+zh37PMd/VNVsi4ChGZjg+BfM7u7iRU3a6fblsIftBEmE2SGJQ51QegqY44+znhtpH+v3vEAVAn7iKXZRPBi+OwTApACTPOmabkQNbmthjGTwptz474OETDGEy610kjlru6xXTVUKlipUPzYf/Zt2dQRlI1FeJ1I51d4ZUW9MIdM53IWWE3KWIl5rIuaTw52G8SDnHNYtinlFZxhX17E=
conda_forge_output_validation: true
